services:
  - type: static
    name: lunation
    env: static
    buildCommand: "npm ci && npm run build"
    staticPublishPath: "dist"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    envVars:
      - key: NODE_VERSION
        value: 20
