name: Deploy to GitHub Pages (docs)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: pages-docs
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (GitHub Pages base)
        run: npm run build:gh

      - name: Prepare docs folder
        run: npm run pages

      - name: Commit and push docs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update docs with latest build [skip ci]'
          file_pattern: docs/**
